s1={1,2,3,4}
s2={1,2}
# print(s1.union(s2))
# s1.update(s2)
# print(s1,s2)
# nums=s1.intersection(s2)
# print(nums)
# s1.intersection_update(s2)
# print(s1)
# intersec=s1.intersection(s2)
# unio=s1.union(s2)
# print(unio.difference(intersec))
# print(s1.isdisjoint(s2))
# print(s2.issubset(s1))
# print(s1.issuperset(s2))
# s1.add(32)
# print(s1)
# s1.remove(1)
# print(s1)
# s1.discard("hai")
# print(s1)
# s1.pop()
# print(s1)
# del s1
# print(s1)
s1.clear()
print(s1)